import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { NotificationsProvider } from "@/context/NotificationsContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const comico = localFont({
  src: "./fonts/Comico-Regular.woff2",
  variable: "--font-comico",
  display: "swap",
});

const cabinetGrotesk = localFont({
  src: "./fonts/CabinetGrotesk-Variable.woff2",
  variable: "--font-cabinet",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinetGrotesk.variable} ${comico.variable} antialiased font-sans flex flex-col min-h-screen selection:bg-primary/20`}
      >
        <AuthProvider>
          <NotificationsProvider>
            <Navbar />
            <main className="flex-grow flex flex-col w-full relative z-0">
              {children}
            </main>
            <Footer />
          </NotificationsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
