/**
 * Reads backend/data/charity_registry.json and writes backend/helpers/db/seed_charities.sql
 * Run from repo root: node backend/scripts/generate_seed_charities.js
 */
const fs = require("fs");
const path = require("path");

const jsonPath = path.join(__dirname, "../data/charity_registry.json");
const outPath = path.join(__dirname, "../helpers/db/seed_charities.sql");

function escapeSql(s) {
  if (s == null) return "NULL";
  return "'" + String(s).replace(/\\/g, "\\\\").replace(/'/g, "''") + "'";
}

const registry = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
const charities = registry.charities || [];

const causeSlugs = new Set();
const regionNames = new Set();
for (const c of charities) {
  (c.focus_values || []).forEach((v) => causeSlugs.add(v));
  (c.regions || []).forEach((r) => regionNames.add(r));
}

const lines = [
  "-- Seed causes, regions, charities from charity_registry.json (generated by scripts/generate_seed_charities.js)",
  "USE empact;",
  ""
];

// Causes (one row per slug)
if (causeSlugs.size > 0) {
  const vals = [...causeSlugs].map((s) => "(" + escapeSql(s) + ")").join(", ");
  lines.push("INSERT INTO causes (cause_slug) VALUES " + vals + " ON DUPLICATE KEY UPDATE cause_slug = cause_slug;");
  lines.push("");
}

// Regions (one row per name)
if (regionNames.size > 0) {
  const vals = [...regionNames].map((s) => "(" + escapeSql(s) + ")").join(", ");
  lines.push("INSERT INTO regions (name) VALUES " + vals + " ON DUPLICATE KEY UPDATE name = name;");
  lines.push("");
}

// Charities
for (const c of charities) {
  lines.push(
    "INSERT INTO charities (charity_id, name, website, donation_url, description, verified) VALUES (" +
      [escapeSql(c.charity_id), escapeSql(c.name), escapeSql(c.website), escapeSql(c.donation_url), escapeSql(c.description), c.verified === true ? "1" : "0"].join(", ") +
      ") ON DUPLICATE KEY UPDATE name = VALUES(name), website = VALUES(website), donation_url = VALUES(donation_url), description = VALUES(description), verified = VALUES(verified);"
  );
}
lines.push("");

// Charity_causes: clear existing and insert (so re-run is idempotent per charity set)
lines.push("-- charity_causes (delete then insert so re-run is idempotent)");
for (const c of charities) {
  const causes = c.focus_values || [];
  if (causes.length === 0) continue;
  lines.push("DELETE FROM charity_causes WHERE charity_id = " + escapeSql(c.charity_id) + ";");
  const vals = causes.map((slug) => "(" + escapeSql(c.charity_id) + ", " + escapeSql(slug) + ")").join(", ");
  lines.push("INSERT INTO charity_causes (charity_id, cause_slug) VALUES " + vals + ";");
}
lines.push("");

// Charity_regions: use subquery to resolve region_id from name
lines.push("-- charity_regions");
for (const c of charities) {
  const regions = c.regions || [];
  if (regions.length === 0) continue;
  lines.push("DELETE FROM charity_regions WHERE charity_id = " + escapeSql(c.charity_id) + ";");
  const vals = regions
    .map((name) => "(" + escapeSql(c.charity_id) + ", (SELECT region_id FROM regions WHERE name = " + escapeSql(name) + " LIMIT 1))")
    .join(", ");
  lines.push("INSERT IGNORE INTO charity_regions (charity_id, region_id) VALUES " + vals + ";");
}

fs.writeFileSync(outPath, lines.join("\n"), "utf8");
console.log("Wrote seed_charities.sql: " + causeSlugs.size + " causes, " + regionNames.size + " regions, " + charities.length + " charities.");
