/**
 * Reads backend/data/opportunities.json and writes backend/helpers/db/seed_opportunities.sql
 * Opportunities store charity_id; donation_url is resolved from charity_registry.json for the DB seed.
 * Run from repo root: node backend/scripts/generate_seed_opportunities.js
 */
const fs = require("fs");
const path = require("path");

const jsonPath = path.join(__dirname, "../data/opportunities.json");
const registryPath = path.join(__dirname, "../data/charity_registry.json");
const outPath = path.join(__dirname, "../helpers/db/seed_opportunities.sql");

function escapeSql(s) {
  if (s == null) return "NULL";
  return "'" + String(s).replace(/\\/g, "\\\\").replace(/'/g, "''") + "'";
}

const list = JSON.parse(fs.readFileSync(jsonPath, "utf8"));
let charityIdToUrl = {};
try {
  const registry = JSON.parse(fs.readFileSync(registryPath, "utf8"));
  (registry.charities || []).forEach((c) => {
    if (c.charity_id) charityIdToUrl[c.charity_id] = c.donation_url || "";
  });
} catch (e) {
  console.warn("Could not load charity_registry.json, donation_url will be empty");
}

const lines = [
  "-- Seed opportunities from opportunities.json (generated by scripts/generate_seed_opportunities.js)",
  "USE empact;",
  ""
];

for (const o of list) {
  const org = o.organization || {};
  const donation = o.donation || {};
  const charityId = donation.charity_id || "";
  const donationUrl = charityId ? (charityIdToUrl[charityId] || "") : (donation.donation_url || "");
  const suggestedAmounts = donation.suggested_amounts != null ? JSON.stringify(donation.suggested_amounts) : null;
  const valuesJson = o.values != null ? JSON.stringify(o.values) : null;

  const cols = [
    "opportunity_id",
    "title",
    "summary",
    "cause",
    "region",
    "org_name",
    "org_website",
    "org_verified",
    "donation_url",
    "suggested_amounts",
    "`values`",
    "ai_confidence_score",
    "date_discovered",
    "source_url"
  ];
  const vals = [
    escapeSql(o.opportunity_id),
    escapeSql(o.title),
    escapeSql(o.summary),
    escapeSql(o.cause),
    escapeSql(o.region),
    escapeSql(org.name),
    escapeSql(org.website),
    org.verified === true ? "1" : "0",
    escapeSql(donationUrl),
    suggestedAmounts != null ? escapeSql(suggestedAmounts) : "NULL",
    valuesJson != null ? escapeSql(valuesJson) : "NULL",
    o.ai_confidence_score != null ? String(o.ai_confidence_score) : "NULL",
    escapeSql(o.date_discovered),
    escapeSql(o.source_url)
  ];
  lines.push(
    "INSERT INTO opportunities (" + cols.join(", ") + ") VALUES (" + vals.join(", ") + ") ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary), cause = VALUES(cause), region = VALUES(region), org_name = VALUES(org_name), org_website = VALUES(org_website), org_verified = VALUES(org_verified), donation_url = VALUES(donation_url), suggested_amounts = VALUES(suggested_amounts), `values` = VALUES(`values`), ai_confidence_score = VALUES(ai_confidence_score), date_discovered = VALUES(date_discovered), source_url = VALUES(source_url);"
  );
}

fs.writeFileSync(outPath, lines.join("\n"), "utf8");
console.log("Wrote " + list.length + " INSERTs to " + outPath);
